; PlatformIO Project Configuration File — Zeta (ζ)
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = board
default_envs = firmware, debugger, bridge

[stm32_common]
platform = ststm32
framework = arduino
build_unflags =
    -D NDEBUG
build_flags =
    -Wl,-Map,${PROJECT_DIR}/.pio/build/${PIOENV}/firmware.map
build_src_filter = +<${PIOENV}/**>

[stm32G431_common]
platform = ${stm32_common.platform}
framework = ${stm32_common.framework}
board = genericSTM32G431CB
upload_protocol = stlink
debug_tool = stlink
build_src_filter = ${stm32_common.build_src_filter}
build_flags =
    ${stm32_common.build_flags}
    -D PIN_SERIAL_TX=PB3
	-D PIN_SERIAL_RX=PB4
    -D DEBUG_UART_BAUDRATE=115200
build_unflags = ${stm32_common.build_unflags}

[native_common]
platform = native
test_framework = unity
lib_deps =
    ArduinoFake
build_flags =
    -std=gnu++17
    -Wno-missing-template-arg-list-after-template-kw

[env:firmware]
platform = ${stm32G431_common.platform}
framework = ${stm32G431_common.framework}
board = ${stm32G431_common.board}
upload_protocol = ${stm32G431_common.upload_protocol}
debug_tool = ${stm32G431_common.debug_tool}
build_src_filter = ${stm32G431_common.build_src_filter}
build_flags = ${stm32G431_common.build_flags}
build_unflags = ${stm32G431_common.build_unflags}

[env:debugger]
platform = ${stm32G431_common.platform}
framework = ${stm32G431_common.framework}
board = ${stm32G431_common.board}
upload_protocol = ${stm32G431_common.upload_protocol}
debug_tool = ${stm32G431_common.debug_tool}
build_src_filter = ${stm32G431_common.build_src_filter}
build_flags = ${stm32G431_common.build_flags}
build_unflags = ${stm32G431_common.build_unflags}

[env:bridge]
platform = ${stm32_common.platform}
framework = ${stm32_common.framework}
board = genericSTM32G030C8T6
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_src_filter = ${stm32_common.build_src_filter}
build_flags = ${stm32_common.build_flags}
build_unflags = ${stm32_common.build_unflags}

[env:Unit]
platform = ${native_common.platform}
test_framework = ${native_common.test_framework}
test_filter = test_unit
lib_deps = ${native_common.lib_deps}
build_flags = ${native_common.build_flags}
